// प्राइसिंग स्क्रीन की हिंदी/English भाषा. {name} जैसे प्लेसहोल्डर params से भरते हैं।
import { useLanguage } from '../context/LanguageContext'

export const STRINGS = {
  // नेविगेशन / सामान्य
  nav_todays_prices: { hi: 'आज की कीमतें', en: "Today's Prices" },
  nav_product_pricing: { hi: 'प्रोडक्ट प्राइसिंग', en: 'Product Pricing' },
  nav_pricing_dashboard: { hi: 'प्राइसिंग डैशबोर्ड', en: 'Pricing Dashboard' },
  nav_pricing_settings: { hi: 'प्राइसिंग सेटिंग', en: 'Pricing Settings' },
  nav_stock: { hi: 'स्टॉक', en: 'Stock' },
  owner_only: { hi: 'यह पेज सिर्फ़ मालिक (एडमिन) के लिए है।', en: 'This page is for the owner (admin) only.' },
  loading: { hi: 'लोड हो रहा है...', en: 'Loading...' },
  save: { hi: 'सेव करें', en: 'Save' },
  saving: { hi: 'सेव हो रहा है...', en: 'Saving...' },
  cancel: { hi: 'रद्द करें', en: 'Cancel' },
  close: { hi: 'बंद करें', en: 'Close' },
  search: { hi: 'सब्ज़ी खोजें...', en: 'Search vegetable...' },
  retry: { hi: 'फिर कोशिश करें', en: 'Try again' },
  per: { hi: 'प्रति', en: 'per' },
  // आज की कीमतें
  tp_title: { hi: 'आज की खरीद कीमतें', en: "Today's Purchase Prices" },
  tp_subtitle: { hi: 'आज की मंडी कीमत डालें — बिक्री कीमत अपने आप निकलेगी। ग्राहक को तब तक कुछ नहीं बदलेगा जब तक आप पब्लिश नहीं करते।', en: 'Enter today\'s market price — selling prices are calculated for you. Customers see nothing new until you publish.' },
  tp_purchase_price: { hi: 'खरीद कीमत', en: 'Purchase price' },
  tp_selling_now: { hi: 'अभी बिक्री कीमत', en: 'Selling now' },
  tp_no_profile: { hi: 'नई सब्ज़ी — पहली बार खरीद कीमत डालें', en: 'New to pricing — enter the first purchase price' },
  tp_recalculate: { hi: 'सभी कीमतें दोबारा निकालें', en: 'RECALCULATE ALL PRICES' },
  tp_preview: { hi: 'पब्लिश से पहले देखें', en: 'Preview before publishing' },
  tp_publish: { hi: 'नई कीमतें पब्लिश करें', en: 'PUBLISH NEW PRICES' },
  tp_publishing: { hi: 'पब्लिश हो रहा है...', en: 'Publishing...' },
  tp_nothing: { hi: 'कोई कीमत नहीं बदलेगी।', en: 'No prices will change.' },
  tp_purchase: { hi: 'खरीद', en: 'Purchase' },
  tp_selling: { hi: 'बिक्री', en: 'Selling' },
  tp_blocked: { hi: 'रुका हुआ — पब्लिश नहीं होगा', en: 'Blocked — will not publish' },
  tp_confirm_loss: { hi: 'मैं समझता हूँ कि इस कीमत पर नुकसान हो सकता है', en: 'I understand this price may cause a loss' },
  tp_published: { hi: 'कीमतें पब्लिश हो गईं: {n}', en: 'Prices published: {n}' },
  tp_conflicts: { hi: 'इन सब्ज़ियों की कीमत किसी और ने अभी बदली है — आपकी कीमत नहीं लगाई गई। पेज रीफ्रेश करके दोबारा डालें:', en: 'These were changed by someone else just now — your values were NOT applied. Refresh and re-enter:' },
  tp_rejected: { hi: 'ये पब्लिश नहीं हुईं:', en: 'These were not published:' },
  tp_queued: { hi: 'इंटरनेट नहीं है। बदलाव फ़ोन में सुरक्षित है — "Pending Sync"। नेटवर्क आते ही अपने आप भेजे जाएंगे।', en: 'You are offline. Your changes are saved on this phone — "Pending Sync". They will be sent when the network returns.' },
  tp_pending_banner: { hi: 'Pending Sync: {n} सब्ज़ियों की कीमतें भेजना बाकी है', en: 'Pending Sync: {n} product price updates waiting to be sent' },
  tp_sync_now: { hi: 'अभी भेजें', en: 'Sync now' },
  tp_discard_pending: { hi: 'पेंडिंग हटाएं', en: 'Discard pending' },
  tp_sync_ok: { hi: 'सिंक हो गया — {n} कीमतें पब्लिश', en: 'Synced — {n} prices published' },
  tp_sync_offline: { hi: 'अभी भी इंटरनेट नहीं है', en: 'Still offline' },
  tp_invalid_row: { hi: 'गलत वैल्यू', en: 'Invalid value' },
  tp_unit_kg: { hi: '/किलो', en: '/kg' },
  tp_filter_changed: { hi: 'सिर्फ़ बदली हुई', en: 'Changed only' },
  tp_changed_count: { hi: '{n} कीमतें बदलेंगी', en: '{n} prices will change' },
  tp_stale_hint: { hi: '{d} दिन से अपडेट नहीं', en: 'Not updated for {d} days' },
  // प्रोडक्ट प्राइसिंग
  pp_title: { hi: 'प्रोडक्ट प्राइसिंग', en: 'Product Pricing' },
  pp_auto: { hi: 'ऑटो', en: 'AUTO' },
  pp_manual: { hi: 'मैनुअल', en: 'MANUAL' },
  pp_auto_price: { hi: 'ऑटो कीमत', en: 'AUTO PRICE' },
  pp_manual_price: { hi: 'मैनुअल कीमत', en: 'MANUAL PRICE' },
  pp_manual_input: { hi: 'आपकी बिक्री कीमत (₹)', en: 'Your selling price (₹)' },
  pp_loss_warning: { hi: 'चेतावनी: इस कीमत पर नुकसान हो सकता है।', en: 'Warning: This price may cause a loss.' },
  pp_loss_confirm: { hi: 'हाँ, इसी कीमत पर सेव करें', en: 'Yes, save this price anyway' },
  pp_min_protection: { hi: 'न्यूनतम कीमत सुरक्षा लागू।', en: 'Minimum price protection applied.' },
  pp_clearance_warning: { hi: 'क्लीयरेंस (नुकसान वाली) कीमत चालू है।', en: 'Clearance (loss) pricing is on.' },
  pp_name: { hi: 'सब्ज़ी का नाम (Hindi)', en: 'Hindi name' },
  pp_name_en: { hi: 'English नाम', en: 'Product name' },
  pp_category: { hi: 'श्रेणी', en: 'Category' },
  pp_purchase_unit: { hi: 'खरीद की इकाई', en: 'Purchase unit' },
  pp_selling_unit: { hi: 'बिक्री की इकाई', en: 'Selling unit' },
  pp_pack_sizes: { hi: 'छोटे पैक भी बेचें', en: 'Also sell small packs' },
  pp_wastage: { hi: 'बर्बादी %', en: 'Wastage %' },
  pp_handling: { hi: 'पैकिंग/हैंडलिंग खर्च (₹)', en: 'Packing/handling cost (₹)' },
  pp_margin: { hi: 'मुनाफ़ा % (टारगेट)', en: 'Target profit margin %' },
  pp_inherit: { hi: 'खाली = श्रेणी का डिफ़ॉल्ट ({v})', en: 'Empty = category default ({v})' },
  pp_stock: { hi: 'मौजूदा स्टॉक', en: 'Current stock' },
  pp_stock_received: { hi: 'स्टॉक कब आया', en: 'Stock received on' },
  pp_stock_age: { hi: 'स्टॉक की उम्र: {d} दिन', en: 'Stock age: {d} day(s)' },
  pp_demand: { hi: 'डिमांड', en: 'Demand' },
  pp_demand_low: { hi: 'कम', en: 'Low' },
  pp_demand_normal: { hi: 'सामान्य', en: 'Normal' },
  pp_demand_high: { hi: 'ज़्यादा', en: 'High' },
  pp_demand_off: { hi: 'डिमांड प्राइसिंग बंद है (सेटिंग में चालू करें)', en: 'Demand pricing is off (enable in settings)' },
  pp_allow_clearance: { hi: 'क्लीयरेंस: लागत से नीचे बेचने की अनुमति', en: 'Clearance: allow selling below safe price' },
  pp_min_safe: { hi: 'न्यूनतम सुरक्षित कीमत', en: 'Minimum safe price' },
  pp_recommended: { hi: 'सुझाई गई कीमत', en: 'Recommended price' },
  pp_customer_price: { hi: 'ग्राहक की कीमत', en: 'Customer price' },
  pp_last_updated: { hi: 'आख़िरी अपडेट: {when} — {who}', en: 'Last updated: {when} by {who}' },
  pp_breakdown: { hi: 'कीमत कैसे बनी', en: 'Price breakdown' },
  pp_admin_only: { hi: 'सिर्फ़ मालिक को दिखता है', en: 'Owner only' },
  pp_history: { hi: 'कीमत का इतिहास', en: 'Price history' },
  pp_no_history: { hi: 'अभी कोई इतिहास नहीं।', en: 'No history yet.' },
  pp_days: { hi: '{n} दिन', en: '{n} days' },
  pp_edit: { hi: 'बदलें', en: 'Edit' },
  pp_saved: { hi: 'सेव हो गया ✅', en: 'Saved ✅' },
  pp_filter_all: { hi: 'सभी', en: 'All' },
  pp_filter_manual: { hi: 'मैनुअल', en: 'Manual' },
  pp_filter_review: { hi: 'समीक्षा चाहिए', en: 'Needs review' },
  pp_filter_low: { hi: 'कम मार्जिन', en: 'Low margin' },
  pp_filter_stale: { hi: 'अपडेट बाकी', en: 'Needs update' },
  pp_margin_now: { hi: 'अभी मार्कअप', en: 'Current markup' },
  pp_not_set: { hi: 'प्राइसिंग सेट नहीं', en: 'Pricing not set' },
  pp_setup: { hi: 'प्राइसिंग शुरू करें', en: 'Set up pricing' },
  pp_purchase_needed: { hi: 'पहले खरीद कीमत डालें', en: 'Enter a purchase price first' },
  pp_changed_elsewhere: { hi: 'यह सब्ज़ी किसी और ने अभी बदली है। पेज रीफ्रेश करें।', en: 'Someone else just changed this. Please refresh.' },
  // ब्रेकडाउन की पंक्तियां
  bd_purchase: { hi: 'खरीद कीमत', en: 'Purchase Price' },
  bd_wastage: { hi: 'बर्बादी जोड़', en: 'Wastage adjustment' },
  bd_effective_cost: { hi: 'असली लागत', en: 'Effective Cost' },
  bd_handling: { hi: 'पैकिंग/हैंडलिंग', en: 'Packing/Handling' },
  bd_base_cost: { hi: 'बेस लागत', en: 'Base Cost' },
  bd_margin: { hi: 'मुनाफ़ा मार्जिन', en: 'Profit Margin' },
  bd_base_recommended: { hi: 'सुझाई गई कीमत', en: 'Recommended Price' },
  bd_demand: { hi: 'डिमांड एडजस्टमेंट ({level})', en: 'Demand adjustment ({level})' },
  bd_freshness: { hi: 'ताज़गी छूट ({d} दिन पुराना)', en: 'Freshness discount ({d} day old)' },
  bd_min_safe: { hi: 'न्यूनतम सुरक्षित कीमत', en: 'Minimum Safe Price' },
  bd_recommended: { hi: 'एडजस्ट के बाद कीमत', en: 'Adjusted price' },
  bd_rounding: { hi: 'राउंडिंग', en: 'Rounding' },
  bd_rounded: { hi: 'ग्राहक की कीमत', en: 'Rounded Customer Price' },
  // वजहें (explanation)
  why_intro: { hi: '₹{price}/{unit} सुझाई गई', en: 'Recommended ₹{price}/{unit}' },
  why_base: { hi: 'खरीद लागत, बर्बादी, पैकिंग और टारगेट मुनाफ़े के आधार पर।', en: 'based on purchase cost, wastage, handling and target margin.' },
  why_COST_UP: { hi: 'खरीद कीमत बढ़ी (₹{from} → ₹{to})', en: 'purchase cost increased (₹{from} → ₹{to})' },
  why_COST_DOWN: { hi: 'खरीद कीमत घटी (₹{from} → ₹{to})', en: 'purchase cost decreased (₹{from} → ₹{to})' },
  why_DEMAND_HIGH: { hi: 'डिमांड ज़्यादा है (+{percent}%)', en: 'demand is high (+{percent}%)' },
  why_DEMAND_LOW: { hi: 'डिमांड कम है ({percent}%)', en: 'demand is low ({percent}%)' },
  why_STOCK_AGE: { hi: 'स्टॉक {days} दिन पुराना है ({percent}% छूट)', en: 'stock is {days} day(s) old ({percent}% discount)' },
  why_MIN_PROTECTION: { hi: 'न्यूनतम कीमत सुरक्षा लगी', en: 'minimum price protection applied' },
  why_CLEARANCE: { hi: 'क्लीयरेंस कीमत की अनुमति है', en: 'clearance pricing is authorised' },
  why_because: { hi: 'क्योंकि', en: 'because' },
  why_and: { hi: 'और', en: 'and' },
  // चेतावनियां
  warn_DEMAND_CLAMPED: { hi: 'डिमांड एडजस्टमेंट सेटिंग की सीमा ({percent}%) पर रोका गया।', en: 'Demand adjustment capped at the configured limit ({percent}%).' },
  warn_MIN_PRICE_PROTECTION_APPLIED: { hi: 'न्यूनतम कीमत सुरक्षा लागू (₹{wouldBe} की जगह ₹{minimumSafePrice})।', en: 'Minimum price protection applied (₹{minimumSafePrice} instead of ₹{wouldBe}).' },
  warn_CLEARANCE_BELOW_SAFE: { hi: 'क्लीयरेंस: कीमत सुरक्षित कीमत ₹{minimumSafePrice} से नीचे है।', en: 'Clearance: price is below the safe price ₹{minimumSafePrice}.' },
  warn_MANUAL_BELOW_SAFE: { hi: 'चेतावनी: इस कीमत पर नुकसान हो सकता है (सुरक्षित कीमत ₹{minimumSafePrice})।', en: 'Warning: This price may cause a loss (safe price ₹{minimumSafePrice}).' },
  // त्रुटियां (इंजन validation)
  err_PURCHASE_PRICE_REQUIRED: { hi: 'खरीद कीमत डालें', en: 'Enter a purchase price' },
  err_PURCHASE_PRICE_NEGATIVE: { hi: 'खरीद कीमत ऋणात्मक नहीं हो सकती', en: 'Purchase price cannot be negative' },
  err_PURCHASE_PRICE_ZERO: { hi: 'खरीद कीमत 0 से ज़्यादा हो', en: 'Purchase price must be above zero' },
  err_WASTAGE_INVALID: { hi: 'बर्बादी % गलत है', en: 'Wastage % is invalid' },
  err_WASTAGE_NEGATIVE: { hi: 'बर्बादी % ऋणात्मक नहीं हो सकती', en: 'Wastage cannot be negative' },
  err_WASTAGE_TOO_HIGH: { hi: 'बर्बादी 100% से कम होनी चाहिए', en: 'Wastage must be below 100%' },
  err_WASTAGE_ABOVE_LIMIT: { hi: 'बर्बादी सेटिंग की सुरक्षित सीमा से ज़्यादा है', en: 'Wastage is above the safe limit in settings' },
  err_MARGIN_INVALID: { hi: 'मुनाफ़ा % गलत है', en: 'Margin % is invalid' },
  err_MARGIN_NEGATIVE: { hi: 'मुनाफ़ा % ऋणात्मक नहीं हो सकता', en: 'Margin cannot be negative' },
  err_MARGIN_ABOVE_LIMIT: { hi: 'मुनाफ़ा % सेटिंग की सीमा से ज़्यादा है', en: 'Margin is above the limit in settings' },
  err_HANDLING_INVALID: { hi: 'हैंडलिंग खर्च गलत है', en: 'Handling cost is invalid' },
  err_UNIT_INVALID: { hi: 'इकाई गलत है', en: 'Invalid unit' },
  err_UNIT_MISMATCH: { hi: 'खरीद और बिक्री की इकाई मेल नहीं खातीं (किलो/ग्राम ↔ नग/गड्डी नहीं बदल सकते)', en: 'Purchase and selling units are not convertible' },
  err_STOCK_AGE_INVALID: { hi: 'स्टॉक की उम्र गलत है', en: 'Stock age is invalid' },
  err_DEMAND_INVALID: { hi: 'डिमांड गलत है', en: 'Invalid demand level' },
  err_PACK_INVALID: { hi: 'पैक साइज़ गलत है', en: 'Invalid pack size' },
  err_MANUAL_PRICE_INVALID: { hi: 'मैनुअल कीमत 0 से ज़्यादा डालें', en: 'Enter a manual price above zero' },
  err_PRICE_NOT_POSITIVE: { hi: 'कीमत 0 से ज़्यादा होनी चाहिए', en: 'Price must be above zero' },
  err_QUANTITY_NEGATIVE: { hi: 'मात्रा ऋणात्मक नहीं हो सकती', en: 'Quantity cannot be negative' },
  err_QUANTITY_INVALID: { hi: 'मात्रा गलत है', en: 'Quantity is invalid' },
  // डैशबोर्ड
  dash_title: { hi: 'प्राइसिंग डैशबोर्ड', en: 'Pricing Dashboard' },
  dash_today: { hi: 'आज', en: 'Today' },
  dash_product_cost: { hi: 'आज के ऑर्डर की सामान-लागत', en: "Product cost of today's orders" },
  dash_sales: { hi: 'आज की बिक्री', en: "Today's sales" },
  dash_gross_margin: { hi: 'अनुमानित ग्रॉस मार्जिन', en: 'Estimated gross margin' },
  dash_delivery_cost: { hi: 'अनुमानित डिलीवरी खर्च', en: 'Estimated delivery cost' },
  dash_contribution: { hi: 'अनुमानित कंट्रीब्यूशन', en: 'Estimated contribution' },
  dash_avg_margin: { hi: 'औसत मार्जिन %', en: 'Average margin %' },
  dash_updated_today: { hi: 'आज अपडेट हुए प्रोडक्ट', en: 'Products updated today' },
  dash_need_update: { hi: 'अपडेट चाहिए', en: 'Needing price update' },
  dash_low_margin: { hi: 'कम मार्जिन प्रोडक्ट', en: 'Low margin products' },
  dash_high_wastage: { hi: 'ज़्यादा बर्बादी वाले', en: 'High wastage products' },
  dash_manual: { hi: 'मैनुअल प्राइस वाले', en: 'Manual pricing' },
  dash_orders_counted: { hi: '{n} ऑर्डर गिने गए (रद्द/असफल छोड़कर)', en: '{n} orders counted (excluding cancelled/failed)' },
  dash_unknown_cost: { hi: '{n} आइटम की लागत पता नहीं (प्राइसिंग सेट नहीं) — मुनाफ़ा बढ़ा-चढ़ा हो सकता है', en: '{n} item(s) have no cost data (pricing not set) — profit may be overstated' },
  dash_alerts: { hi: 'अलर्ट', en: 'Alerts' },
  dash_no_alerts: { hi: 'सब ठीक है ✅', en: 'All good ✅' },
  dash_review_card: { hi: '{n} प्रोडक्ट की कीमत देखनी है', en: '{n} products need price review' },
  dash_close_margin_card: { hi: '{n} प्रोडक्ट न्यूनतम मार्जिन के पास हैं', en: '{n} products are close to minimum margin' },
  // अलर्ट
  al_purchase_up: { hi: '{name}: खरीद कीमत ₹{from} से ₹{to} हुई (+{percent}%)। बिक्री कीमत देखें।', en: '{name} purchase price increased from ₹{from} to ₹{to} (+{percent}%). Review selling price.' },
  al_purchase_down: { hi: '{name}: खरीद कीमत ₹{from} से ₹{to} हुई ({percent}%)। बिक्री कीमत घटाने पर विचार करें।', en: '{name} purchase price decreased from ₹{from} to ₹{to} ({percent}%). Consider lowering the price.' },
  al_margin_low: { hi: '{name}: मार्जिन सिर्फ़ {percent}% (सीमा {threshold}%)।', en: '{name}: margin is only {percent}% (limit {threshold}%).' },
  al_below_safe: { hi: '{name}: कीमत ₹{price} सुरक्षित कीमत ₹{minSafe} से नीचे है!', en: '{name}: price ₹{price} is below the safe price ₹{minSafe}!' },
  al_high_wastage: { hi: '{name}: बर्बादी {percent}% — असामान्य रूप से ज़्यादा।', en: '{name}: wastage is {percent}% — unusually high.' },
  al_stale: { hi: '{name}: {days} दिन से कीमत अपडेट नहीं हुई।', en: '{name}: price not updated for {days} days.' },
  al_no_profile: { hi: '{name}: प्राइसिंग सेट नहीं है।', en: '{name}: pricing is not set up.' },
  chip_purchase_up: { hi: 'खरीद ▲{percent}%', en: 'Cost ▲{percent}%' },
  chip_purchase_down: { hi: 'खरीद ▼{percent}%', en: 'Cost ▼{percent}%' },
  chip_margin_low: { hi: 'कम मार्जिन {percent}%', en: 'Low margin {percent}%' },
  chip_below_safe: { hi: 'घाटे की कीमत!', en: 'Below safe price!' },
  chip_high_wastage: { hi: 'बर्बादी {percent}%', en: 'Wastage {percent}%' },
  chip_stale: { hi: 'अपडेट बाकी', en: 'Needs update' },
  chip_no_profile: { hi: 'प्राइसिंग नहीं', en: 'No pricing' },
  // सेटिंग
  ps_title: { hi: 'प्राइसिंग सेटिंग', en: 'Pricing Settings' },
  ps_rounding: { hi: 'कीमत राउंडिंग', en: 'Price rounding' },
  ps_rounding_main: { hi: 'मुख्य कीमत', en: 'Main price' },
  ps_rounding_small: { hi: 'छोटे पैक (500g, 250g...)', en: 'Small packs (500g, 250g...)' },
  rm_ceil_1: { hi: 'अगले ₹1 तक ऊपर (₹41.53 → ₹42)', en: 'Up to next ₹1 (₹41.53 → ₹42)' },
  rm_nearest_1: { hi: 'सबसे पास का ₹1', en: 'Nearest ₹1' },
  rm_nearest_5: { hi: 'सबसे पास का ₹5', en: 'Nearest ₹5' },
  rm_psychological: { hi: 'साइकोलॉजिकल (₹40 → ₹39, ₹50 → ₹49)', en: 'Psychological (₹40 → ₹39, ₹50 → ₹49)' },
  rm_ceil_0_5: { hi: 'अगले ₹0.50 तक ऊपर', en: 'Up to next ₹0.50' },
  rm_nearest_0_5: { hi: 'सबसे पास का ₹0.50', en: 'Nearest ₹0.50' },
  rm_none: { hi: 'राउंड नहीं (पैसे तक)', en: 'No rounding (to paise)' },
  ps_protection: { hi: 'न्यूनतम कीमत सुरक्षा', en: 'Minimum price protection' },
  ps_min_safety: { hi: 'अतिरिक्त सुरक्षा मार्जिन % (0 = लागत से नीचे कभी नहीं)', en: 'Extra safety margin % (0 = never below cost)' },
  ps_limits: { hi: 'सुरक्षित सीमाएं', en: 'Safe limits' },
  ps_max_wastage: { hi: 'अधिकतम बर्बादी % (100 से कम)', en: 'Max wastage % (below 100)' },
  ps_max_margin: { hi: 'अधिकतम मुनाफ़ा %', en: 'Max margin %' },
  ps_defaults: { hi: 'नई सब्ज़ी के डिफ़ॉल्ट', en: 'Defaults for new products' },
  ps_freshness: { hi: 'ताज़गी (स्टॉक की उम्र) छूट', en: 'Freshness (stock age) discount' },
  ps_freshness_on: { hi: 'ताज़गी छूट चालू', en: 'Freshness discount on' },
  ps_tier_days: { hi: 'कम से कम दिन', en: 'From day' },
  ps_tier_pct: { hi: 'छूट %', en: 'Discount %' },
  ps_add_tier: { hi: '+ स्तर जोड़ें', en: '+ Add tier' },
  ps_demand: { hi: 'डिमांड प्राइसिंग', en: 'Demand pricing' },
  ps_demand_on: { hi: 'डिमांड प्राइसिंग चालू', en: 'Demand pricing on' },
  ps_demand_low: { hi: 'कम डिमांड %', en: 'Low demand %' },
  ps_demand_high: { hi: 'ज़्यादा डिमांड %', en: 'High demand %' },
  ps_demand_max_up: { hi: 'अधिकतम बढ़त %', en: 'Max increase %' },
  ps_demand_max_down: { hi: 'अधिकतम कटौती %', en: 'Max decrease %' },
  ps_alerts: { hi: 'अलर्ट सीमाएं', en: 'Alert thresholds' },
  ps_alert_change: { hi: 'खरीद कीमत बदलाव पर अलर्ट (%)', en: 'Alert on purchase change (%)' },
  ps_alert_low_margin: { hi: 'कम मार्जिन सीमा (%)', en: 'Low margin limit (%)' },
  ps_alert_wastage: { hi: 'ज़्यादा बर्बादी सीमा (%)', en: 'High wastage limit (%)' },
  ps_alert_stale: { hi: 'इतने दिन अपडेट न हो तो अलर्ट', en: 'Alert if not updated for (days)' },
  ps_costs: { hi: 'ऑर्डर-मुनाफ़े के अनुमान', en: 'Order profit estimates' },
  ps_delivery_cost: { hi: 'हर ऑर्डर का असली डिलीवरी खर्च (₹)', en: 'Actual delivery cost per order (₹)' },
  ps_payment_pct: { hi: 'पेमेंट चार्ज (%)', en: 'Payment charge (%)' },
  ps_costs_note: { hi: 'नए ऑर्डर पर लागू। पुराने ऑर्डर का हिसाब नहीं बदलता।', en: 'Applies to new orders. Past orders keep their original figures.' },
  ps_min_order: { hi: 'न्यूनतम ऑर्डर (₹)', en: 'Minimum order value (₹)' },
  ps_delivery_rules: { hi: 'डिलीवरी शुल्क के नियम', en: 'Delivery charge rules' },
  ps_delivery_hint: { hi: 'कार्ट इस राशि या उससे ऊपर हो तो शुल्क। शुल्क 0 = मुफ़्त डिलीवरी।', en: 'Fee applies when the cart is at or above this amount. Fee 0 = free delivery.' },
  ps_rule_from: { hi: 'कार्ट ≥ (₹)', en: 'Cart ≥ (₹)' },
  ps_rule_fee: { hi: 'शुल्क (₹)', en: 'Fee (₹)' },
  ps_add_rule: { hi: '+ नियम जोड़ें', en: '+ Add rule' },
  ps_remove: { hi: 'हटाएं', en: 'Remove' },
  ps_category_rules: { hi: 'श्रेणी के डिफ़ॉल्ट नियम', en: 'Category default rules' },
  ps_rule_wastage: { hi: 'बर्बादी %', en: 'Wastage %' },
  ps_rule_margin: { hi: 'मुनाफ़ा %', en: 'Margin %' },
  ps_rule_handling: { hi: 'हैंडलिंग ₹', en: 'Handling ₹' },
  ps_rule_type_regular: { hi: 'सामान्य (कम बर्बादी)', en: 'Regular / low wastage' },
  ps_rule_type_normal: { hi: 'नॉर्मल', en: 'Normal' },
  ps_rule_type_leafy: { hi: 'पत्तेदार', en: 'Leafy' },
  ps_rule_type_premium: { hi: 'प्रीमियम/एक्सोटिक', en: 'Premium / exotic' },
  ps_apply_preset: { hi: 'सुझाया डिफ़ॉल्ट भरें', en: 'Fill suggested defaults' },
  ps_saved: { hi: 'सेटिंग सेव हो गई ✅', en: 'Settings saved ✅' },
  ps_fix_errors: { hi: 'कृपया लाल वैल्यू ठीक करें।', en: 'Please fix the highlighted values.' },
  ps_audit: { hi: 'हाल के बदलाव (ऑडिट)', en: 'Recent changes (audit)' },
  // स्टॉक
  st_title: { hi: 'स्टॉक', en: 'Stock' },
  st_qty: { hi: 'मात्रा', en: 'Quantity' },
  st_received: { hi: 'स्टॉक आया', en: 'Received' },
}

export function fmt(template, params = {}) {
  return String(template).replace(/\{(\w+)\}/g, (_, k) => (params[k] === undefined || params[k] === null ? '' : params[k]))
}

export function translatePT(key, language = 'hi', params) {
  const entry = STRINGS[key]
  if (!entry) return key
  return fmt(entry[language] ?? entry.hi, params)
}

export function usePT() {
  const { language } = useLanguage()
  const pt = (key, params) => translatePT(key, language, params)
  pt.language = language
  return pt
}

/** इंजन की explanation.reasons → पूरा वाक्य */
export function explainSentence(result, language = 'hi') {
  const ex = result?.explanation
  if (!ex) return ''
  const unit = result.baseUnit || 'kg'
  const head = translatePT('why_intro', language, { price: result.roundedPrice, unit })
  if (!ex.reasons.length) return `${head} ${translatePT('why_base', language)}`
  const parts = ex.reasons.map((r) => translatePT(`why_${r.code}`, language, r.params))
  const and = ` ${translatePT('why_and', language)} `
  const joined = parts.length === 1 ? parts[0] : parts.slice(0, -1).join(', ') + and + parts[parts.length - 1]
  return `${head} ${translatePT('why_because', language)} ${joined}.`
}
